name: deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
            - name: Setup Known Hosts
              run: |
                echo "${{secrets.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
                chmod 644 ~/.ssh/known_hosts
            - name: SSH Deploy
              run: |
                ssh -v ${{secrets.SSH_USERNAME}}@${{secrets.SSH_PUBLIC_IP}} "
                cd CI-CDwithDocker
                git pull || exit 1
                npm install || exit 1
                npm run build || exit 1
                sudo npm install wait-on -g || exit 1
                sudo pkill node || exit 1
                sudo npm run start & npm wait-on http://localhost --timeout 30000
                exit
                "
            
